# Build stage
FROM node:20-alpine

# Set working directory
WORKDIR /app

ADD . .

ARG NEXT_PUBLIC_API_URL

RUN npm install -g pnpm
RUN pnpm install
RUN pnpm build

# Expose the port
EXPOSE 3000

# Start the application
CMD ["pnpm", "start"]